baseurl: "https://ukarcodeclub.netlify.app/"
DefaultContentLanguage: en
title: UKA R Code Club
theme: beautifulhugo
pygmentsStyle: trac
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
Params:
  comments: yes
  commit: no
  dateFormat: January 2, 2006
  delayDisqus: yes
  favicon: img/favicon.ico
  logo: img/avatar-icon.png
  mainSections:
    - post
    - posts
  readingTime: yes
  rss: no
  showRelatedPosts: yes
  socialShare: no
  subtitle: A weblog to document the activities of the UKA R Code Club
  useHLJS: yes
  wordCount: yes
Author:
  email: rpauli@ukaachen.de
  github: paulirom
  name: Roman Pauli
menu:
  main:
    - name: Blog
      url: ''
      weight: 1
    - name: About
      url: page/about/
      weight: 3
    - name: Tags
      url: tags
      weight: 3
